# Generated by Django 5.0.3 on 2024-04-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_service_server'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='prefred_ip',
            new_name='preferred_ip',
        ),
    ]
